### ISSUE TITLE
Red Hat Connect inclusion and (sub)licensing

### ISSUE THREAD

**Issue by jsm84** [tembleking/rhc-manager#1]
I was inquiring on possible inclusion of this tool into our new tooling section at RHC4TP/tooling. We (the Partner Ecosystem team at Red Hat) would like to credit you as well as Sysdig for contributing this API tool. The only issue is, we would need to know the open-source license you've selected for distribution, as we can't publish code that is unlicensed. I will be using the Apache v2 license moving forward for my own contributions to that repo (since it matches the boto3/aws python SDK and also all CNCF projects).

**Comment by tembleking** [comment]
Sure! The software has now a license, feel free to use it! :blush:
